table Item
	lineageTag: c288924f-72e6-46c1-b123-ec0715cc6ba0

	column ItemID
		dataType: int64
		isHidden
		lineageTag: 7dfcb2e3-c0e9-4f7f-9cc2-3febc841a725
		summarizeBy: none
		sourceColumn: ItemID

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Segment
		dataType: string
		lineageTag: ee57f759-0475-415e-b36d-80ddee645ed3
		summarizeBy: none
		sourceColumn: Segment

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Category
		dataType: string
		lineageTag: f96ddc66-605f-491b-a3f5-db640aa0276b
		summarizeBy: none
		sourceColumn: Category

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Buyer
		dataType: string
		lineageTag: a2513bed-2a21-4865-9860-d2b19feda724
		summarizeBy: none
		sourceColumn: Buyer

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

	column FamilyNane
		dataType: string
		lineageTag: 19dc4ae6-a85e-4efa-aeb0-904d79987dc4
		summarizeBy: none
		sourceColumn: FamilyNane

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

	partition Item = m
		source =
				let
				    Source = Sql.Database(".", "RetailBIDW", [Query="SELECT [ItemID]#(lf)     -- ,[SupplierID]#(lf)      --,[Name]#(lf)      --,[Description]#(lf)      --,[BrandName]#(lf)      ,[ResponsibleBuyerLastName] +', ' + [ResponsibleBuyerFirstName] Buyer#(lf)      ,left([SegmentName], 4) [SegmentName]#(lf)     -- ,[SegmentID]#(lf)      ,left([FamilyName], 3) FamilyNane#(lf)    --  ,[FamilyID]#(lf)      ,[ClassName]#(lf)     -- ,[ClassID]#(lf)   --   ,[ItemCost]#(lf)     -- ,[OriginalItemCost]#(lf)  FROM [RetailBIDW].[dbo].[Item_Dimension]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"ItemID", "ItemID"}, {"SegmentName", "Segment"}, {"ClassName", "Category"}, {"Buyer", "Buyer"}, {"FamilyNane", "FamilyNane"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ItemID", Int64.Type}, {"Segment", type text}, {"Category", type text}, {"Buyer", type text}, {"FamilyNane", type text}})
				in
				    #"Changed Type"

